// Models / Types

// Role – Represents the access level a user can have in the system.
export type Role = "guest" | "user" | "admin";

// User – Stores information about a system user, such as ID, email, role, and name.
export interface User {
  id: number;
  email: string;
  role: Role;
  name?: string;
}

// Budget – Represents a budget record for a specific financial period.
export interface Budget {
  id: number;
  name: string;
  period: string;
}

// Transaction – Stores a single income or expense entry with amount, date, and category.
export interface Transaction {
  id: number;
  type: "income" | "expense";
  amount: number;
  date: string;
  categoryId: number;
  notes?: string;
}

// Category – Represents a classification group for financial transactions.
export interface Category {
  id: number;
  name: string;
}

// Template – Stores reusable preset data for budgeting or planning.
export interface Template {
  id: number;
  name: string;
  data?: any;
}

// Report – Contains calculated financial summary data for a chosen period.
export interface Report {
  period: string;
  totals: any;
}

// PlanResult – Holds projected financial planning results generated by the backend.
export interface PlanResult {
  summary: string;
  projections: any;
}

// Feedback – Represents user-submitted feedback that admins can review.
export interface Feedback {
  id: number;
  status: string;
  message: string;
}

// Ticket – Represents a customer support ticket submitted by the user.
export interface Ticket {
  id: number;
  status: string;
  message: string;
}

// AppState – Holds all shared application data used across the frontend.
export interface AppState {
  user?: User | null;
  budgets: Budget[];
  transactions: Transaction[];
  categories: Category[];
  templates: Template[];
  reports?: Report | null;
}

// Default application state factory
export const defaultAppState = (): AppState => ({
  user: null,
  budgets: [],
  transactions: [],
  categories: [],
  templates: [],
  reports: null,
});

// HttpClient – Provides wrapper methods for GET, POST, PUT, and DELETE requests to the backend.
export class HttpClient {
  constructor(public baseUrl: string = "") {}

  private buildUrl(path: string) {
    if (path.startsWith("http")) return path;
    return `${this.baseUrl.replace(/\/$/, "")}/${path.replace(/^\//, "")}`;
  }

  async get<T = any>(path: string): Promise<T> {
    const url = this.buildUrl(path);
    const res = await fetch(url, { method: "GET", credentials: "include" });
    if (!res.ok) throw new Error(`GET ${url} failed: ${res.statusText}`);
    return res.json();
  }

  async post<T = any>(path: string, body: any): Promise<T> {
    const url = this.buildUrl(path);
    const res = await fetch(url, {
      method: "POST",
      body: JSON.stringify(body),
      credentials: "include",
      headers: { "Content-Type": "application/json" },
    });
    if (!res.ok) throw new Error(`POST ${url} failed: ${res.statusText}`);
    return res.json();
  }

  async put<T = any>(path: string, body: any): Promise<T> {
    const url = this.buildUrl(path);
    const res = await fetch(url, {
      method: "PUT",
      body: JSON.stringify(body),
      credentials: "include",
      headers: { "Content-Type": "application/json" },
    });
    if (!res.ok) throw new Error(`PUT ${url} failed: ${res.statusText}`);
    return res.json();
  }

  async del<T = any>(path: string): Promise<T> {
    const url = this.buildUrl(path);
    const res = await fetch(url, { method: "DELETE", credentials: "include" });
    if (!res.ok) throw new Error(`DELETE ${url} failed: ${res.statusText}`);
    return res.json();
  }
}

// StateStore – Manages global application state and notifies subscribers when it changes.
type Listener = (state: AppState) => void;

export class StateStore {
  private state: AppState;
  private listeners: Set<Listener> = new Set();

  constructor(initial?: AppState) {
    this.state = initial ?? defaultAppState();
  }

  getState(): AppState {
    return {
      ...this.state,
      budgets: [...this.state.budgets],
      transactions: [...this.state.transactions],
      categories: [...this.state.categories],
      templates: [...this.state.templates],
    };
  }

  setState(patch: Partial<AppState>): void {
    this.state = { ...this.state, ...patch };
    this.emit();
  }

  subscribe(listener: Listener): () => void {
    this.listeners.add(listener);
    listener(this.getState());
    return () => this.listeners.delete(listener);
  }

  private emit() {
    const current = this.getState();
    for (const l of this.listeners) l(current);
  }
}

// Router – Controls the navigation between different pages of the frontend.
export interface PageConstructor {
  new (...args: any[]): Page;
}

export class Router {
  private routes = new Map<string, PageConstructor>();
  private currentPage?: Page;
  private rootEl: HTMLElement | null = null;

  register(route: string, PageCtor: PageConstructor) {
    this.routes.set(route, PageCtor);
  }

  navigate(path: string) {
    const PageCtor = this.routes.get(path);
    if (!PageCtor) {
      console.warn(`No route registered for ${path}`);
      return;
    } 
    if (!this.rootEl) throw new Error("Router root element not mounted.");

    if (this.currentPage) this.currentPage.unmount();

    this.currentPage = new PageCtor();
    this.currentPage.mount(this.rootEl);
  }

  mount(rootEl: HTMLElement) {
    this.rootEl = rootEl;
  }
}

// Page – Serves as the base class that all pages extend and controls rendering into the root HTML element.
export abstract class Page {
  protected rootEl?: HTMLElement;

  mount(rootEl: HTMLElement): void {
    this.rootEl = rootEl;
    this.render(undefined as any);
  }

  unmount(): void {
    if (this.rootEl) this.rootEl.innerHTML = "";
    this.rootEl = undefined;
  }

  abstract render(state: AppState | undefined): void;
}

// AuthService – Handles authentication logic including login, registration, and session retrieval.
export class AuthService {
  constructor(private http: HttpClient) {}

  async login(email: string, password: string): Promise<User> {
    return this.http.post<User>("auth/login", { email, password });
  }

  async logout(): Promise<void> {
    await this.http.post("auth/logout", {});
  }

  async register(data: any): Promise<User> {
    return this.http.post<User>("auth/register", data);
  }

  async getSession(): Promise<User | null> {
    try {
      return await this.http.get<User>("auth/session");
    } catch {
      return null;
    }
  }
}

// BudgetService – Fetches budgets, transactions, categories, and templates from the backend.
export class BudgetService {
  constructor(private http: HttpClient) {}

  async listBudgets(): Promise<Budget[]> {
    return this.http.get<Budget[]>("budgets");
  }

  async createBudget(input: Partial<Budget>): Promise<Budget> {
    return this.http.post<Budget>("budgets", input);
  }

  async listTransactions(filter?: any): Promise<Transaction[]> {
    return this.http.get<Transaction[]>("transactions" + (filter ? `?${new URLSearchParams(filter).toString()}` : ""));
  }

  async listCategories(): Promise<Category[]> {
    return this.http.get<Category[]>("categories");
  }

  async listTemplates(): Promise<Template[]> {
    return this.http.get<Template[]>("templates");
  }
}

// ReportService – Generates financial reports such as monthly summaries and category breakdowns.
export class ReportService {
  constructor(private http: HttpClient) {}

  async summary(month: string): Promise<Report> {
    return this.http.get<Report>(`reports/summary?month=${encodeURIComponent(month)}`);
  }

  async byCategory(range: { from: string; to: string }): Promise<Report> {
    return this.http.post<Report>("reports/by-category", range);
  }
}

// PlanningService – Generates long-term financial projections for college, career, and retirement.
export class PlanningService {
  constructor(private http: HttpClient) {}

  async collegePlan(input: any): Promise<PlanResult> {
    return this.http.post<PlanResult>("planning/college", input);
  }

  async careerPlan(input: any): Promise<PlanResult> {
    return this.http.post<PlanResult>("planning/career", input);
  }

  async retirementPlan(input: any): Promise<PlanResult> {
    return this.http.post<PlanResult>("planning/retirement", input);
  }
}



